### ISSUE TITLE
Mapping Manual link seems to be broken in help

### ISSUE THREAD

**Issue by illwieckz** [NeonKnightOA/oagamepack#10]
Hi, experimenting with OpenArena to help Zero Kahn to figure out if the bugs he faces with NetRadiant are related to NetRadiant or not (see https://gitlab.com/xonotic/netradiant/-/issues/151 ), I did some stuff with NetRadiant and OpenArena, and noticed the https://openarena.fandom.com/wiki/Mapping_Manual link in help is a broken link.

**Comment by NeonKnightOA** [comment]
The second word begins with lowercase 🤦 dammit Fandom/Wikia/theirversionofMediawiki and their case sensitiveness. (It's Mapping_manual). I'll fix this one now.

I had the idea of distilling the mapping manual and creating a proper version with all bases covered in Markdown format, but I'm lacking the time to do so lately.

**Comment by NeonKnightOA** [comment]
Fixed, thanks for reporting. 🍻
