### ISSUE TITLE
The script version

### ISSUE THREAD

**Issue by sago007** [NeonKnightOA/oagamepack#3]
I have created a branch sago_script_version that I want to merge into master at some point. At the moment it can only create the entities.ent file but I have started placing it hear. 

It may be a good idea for people to test if they can actually run the "create_output.sh" or "create_output.bat" before actually merging it into master.

**Comment by The-Gig** [comment]
I would like to give it a try.
But, apart from the fact I haven't python installed, for me it's a problem to download the whole package (I can't manually "save as" every single file in the repository one by one...).
And I tried Github desktop a few years ago, and I was really disappointed by it. So I only use github using the web interface at the moment.
I fear it may be too much to ask for a complete "download package", just to do a small test...

**Comment by sago007** [comment]
There is a "Download ZIP" option in Github if you choose download.
Python is properly the biggest problem. I tried installing on Windows with https://www.anaconda.com/download/ . It is quite big. The only alternative I can come up with is compiling a binary and commit it instead.

**Comment by The-Gig** [comment]
Downloaded Anaconda 3.6. Its installation programs asks me if I want to add it to PATH, but _does not recommend doing it_ (it says doing so may cause problems which may require to uninstall and reinstall Anaconda - I have no idea how something ordinary as adding a path to PATH may cause such big problems). 
If I don't add it to the path, then should I launch Anaconda first, and then launch "create_output.bat" from within it? Or should I customize the .bat to specify the full path to python executable?

**Comment by sago007** [comment]
The Anaconda install should be able to start a shell with the correct paths setup. From this you should be able to navigate to the directory with the bat file and run it. It should be executed from the directory and not with the full path.

**Comment by The-Gig** [comment]
Okay. Downloaded and extracted the zip of the script version branch. Launched "create_output.bat" from Anaconda Prompt. It looks like it works, it created entities.ent file in the apposite folder.

**Comment by sago007** [comment]
One question is the ability to run it. Another thing is if it actually works in the work flow. Does the guide on https://docs.google.com/document/d/1xmpfXyfEj-K2Jjw-cRO470kog62AId5NVvTteQ-tXz4/edit?usp=sharing actually make sense?
Does it provide value in its current form?

**Comment by The-Gig** [comment]
That kind of test will require some time, I'm quite busy in these days...

**Comment by sago007** [comment]
It wasn't an attempt to put any kind of pressure on you. i myself are quite busy.

**Comment by NeonKnightOA** [comment]
I'm fine with whatever measure is required to make the gamepack GPL. The only thing I want the contributors to bear in mind is that the Radiant gamepack installers will do a checkout of the repository in order to obtain the required gamepack, hence why we need fully-ready-to-use versions of entities.def and entities.ent in the respective baseoa folders.

**Comment by The-Gig** [comment]
> the Radiant gamepack installers will do a checkout of the repository in order to obtain the required gamepack
What? I don't get what you mean... are Radiant installers aware of the existence of this github repo or what?

**Comment by NeonKnightOA** [comment]
The Radiant repos have a file, called download-gamepacks.sh. They contain a list of repos with the license and download link. During the building phase, the makefile calls this file, checks which gamepacks have a GPL license (it can also download everything else, provided it has a certain switch), and download and install them. Recent updates to the NetRadiant repos added this repository instead of the original non-GPL OA gamepack.

**Comment by The-Gig** [comment]
... but this is unfinished... ouch...

**Comment by NeonKnightOA** [comment]
A barebones entities.ent and entities.def should be enough until the proper solution can be put in place.

**Comment by sago007** [comment]
> ... but this is unfinished... ouch...
and it will always be unfinished...
Software is never complete. It is just released. There is always room for improvement.
You have much higher motivation if things quickly goes into the final product. It is hard for perfectionists to accept. Just always follow the boy scout rule: leave the campground cleaner than you found it.

Which is also why I want to merge sago_script_version into master sooner rather than later. I just don't want to force it into master without your approval.

**Comment by NeonKnightOA** [comment]
As long as the solution can drop ready-to-be-used files into the respective folders (this is important because of what I've said above), it's fine by me.

**Comment by sago007** [comment]
@NeonKnightOA Which editor are you using for testing the "def" files?

I have used https://github.com/Garux/netradiant-custom for testing the ent file. I have realized that there are two ent files and that have only generated one but that is trivial to solve.

**Comment by NeonKnightOA** [comment]
I'm using the same editor. In fact, it's been my main editor since quite some time.

About the two entity files, one is for regular 0.8.8 OA and the other for OAX (considering that OAX has some entities and function which don't appear in 0.8.8).
