### ISSUE TITLE
restore git history: rewritten tree is ready (force-push required)

### ISSUE THREAD

**Issue by illwieckz** [NeonKnightOA/oagamepack#3]
Hi, I restored history from a local copy of the old repository I found in my netradiant build directory.
I noticed I missed some readme editions so I created a commit for the missing change.
Then I imported the minor changes from your newer tree.
Then I entirely rewrote the history to only keep the files the newer repository has.

So there is absolutely no difference in files but all the commits having modified remaining files are there with date, author and correct commit title, except the one I had to redo by hand.

I uploaded the restored tree in a branch named `history` on my fork, this is the `history` tree: https://github.com/illwieckz/oagamepack/commits/history

I also made some extra work on another branch named `pngbrute`. This branch is the exact same tree but png files were optimized by several PNG optimizers then bruteforced with [zopfli](https://en.wikipedia.org/wiki/Zopfli) compression algorithm to reduce their file size. While saving 30% file space, the saved file space is not impressive since the files themselves are lightweight at first. This reduces the `entity_icons` directory weight from 42.362 KB to 29.976 KB (12.386 KB saved).

This is the `pngbrute` tree: https://github.com/illwieckz/oagamepack/commits/pngbrute

To replace the current master tree with one of those reworked trees, you can do this way:

With the `history` tree:

```sh
git clone -b history --single-branch git@github.com:illwieckz/oagamepack.git oagamepack-history
cd oagamepack-history
git remote add upstream git@github.com:NeonKnightOA/oagamepack.git
git branch -m master
git push --force --set-upstream upstream master
```

With the `pngbrute` tree:

```sh
git clone -b pngbrute --single-branch git@github.com:illwieckz/oagamepack.git oagamepack-pngbrute
cd oagamepack-pngbrute
git remote add upstream git@github.com:NeonKnightOA/oagamepack.git
git branch -m master
git push --force --set-upstream upstream master
```

**Comment by NeonKnightOA** [comment]
Hi! At the moment I can't do much on this, as my Linux partition went belly up and I've been getting connection issues. However this should be looked upon by the other admins of this repo as well.

**Comment by NeonKnightOA** [comment]
OK, I can now take a look at this. I've made some recent commits today with missing infos, so my initial concern is... how is this going to affect the new commits?

**Comment by illwieckz** [comment]
I updated those branch with your new commits (otherwise, yes, those new commits would have been lost). You can check on links above that the reconstructed branches now features them.
Just pick the one you want to be the master branch and there you go. :-)

**Comment by NeonKnightOA** [comment]
Neat! I'll try my hand before the day ends.

**Comment by NeonKnightOA** [comment]
I'll be using the pngbrute branch.

**Comment by NeonKnightOA** [comment]
Well, it's done. I had to replace the github.com: lines with direct URLs in order to work, since otherwise I had auth problems.

**Comment by illwieckz** [comment]
Awesome! That's good! :+1:
