### ISSUE TITLE
Stuff missing in target_speaker

### ISSUE THREAD

**Issue by The-Gig** [NeonKnightOA/oagamepack#4]
Hi! I just noticed that here
https://github.com/NeonKnightOA/oagamepack/blob/master/oa.game/baseoa/entities.ent
the spawnflags "looped_on" _is missing_ in target_speaker definition. I don't know if other files need to be fixed for that, too.

Further looking into at target_speaker, I see that it currently also _doesn't mention_ these keys:
- noise
- wait
- random
- targetname

Also, maybe "notes" mentioning that it's possible to use like "*falling1" to play character-specific sounds, that sounds _have to_ be mono, that 32 bit pcm is not supported and that ogg work only if the extension is omitted would be useful.

**Comment by NeonKnightOA** [comment]
Just on that file or all of this also applies to entities.def?
It's useful to know this.

**Comment by The-Gig** [comment]
Also in https://github.com/NeonKnightOA/oagamepack/blob/master/oa.game/baseoa/entities.def
target_speaker is quite scarce in infos, it doesn't mention noise, wait, random, targetname, and has got no notes. But it seems to mention "looped_on" flag existence (although not explaining its behavior).

**Comment by NeonKnightOA** [comment]
Solved in NeonKnightOA/oagamepack@ba78475cb63d0f67254d8c248f4c64dd2da20de5. The problem also affected other entities.
