### ISSUE TITLE
Infos removed from notes?

### ISSUE THREAD

**Issue by The-Gig** [NeonKnightOA/oagamepack#5]
I noticed that "notes" in current gamepack, while added some useful infos, seem to _lack_ other useful infos which were in old gamepack.

As example, these are the notes for "ammo_lightning" in old gamepack:

> The amount of time it takes for an item in the team to respawn is determined by the "wait" value of the item that was picked up previously. So if one of the items in the team has it's "wait" key set to -1 (never respawn), the random respawning cycle of the teamed items will stop after that item is picked up.
> 
> When the random key is set, its value is used to calculate a minimum and a maximum delay. The final time delay will be a random value anywhere between the minimum and maximum values: (min delay = wait - random) (max delay = wait + random).
> 

And these are the notes for the same in current gamepack:

> Values for the 'gametype' and '!gametype' keys need to be separated by spaces. The valid values are the following for each gametype:
> - ffa: Free For All
> - tournament: Tournament
> - single: Single Player
> - team: Team Deathmatch
> - ctf: Capture the Flag and CTF Elimination
> - oneflag: One Flag CTF
> - obelisk: Overload
> - harvester: Harvester
> - elimination: Elimination
> - lms: Last Man Standing
> - dd: Double Domination
> - dom: Single Domination
> - pos: Possession
> Unless a specific kind of gameplay requires it or you plan to team up items, DON'T set the 'wait' or 'count' keys. You don't want to mess with your players' timing of the items or what the players expect from the items they pick up. If you want to limit an entity to make it viable on your map, rethink the layout of your map so the entity doesn't end overpowered.
> Upon activation of the targets, all shaders/textures in the map with the shader/texture mentioned in targetShaderName will change to the shader/texture mentioned in targetShaderNewName. This is useful for on/off switches, for example.

What about changing to something like:

> Values for the 'gametype' and '!gametype' keys need to be separated by spaces. The valid values are the following: ffa tournament single team ctf oneflag obelisk harvester elimination lms dd dom pos
> 
> In case of "teamed" items, the respawn time depends from the "wait" of the previously picked up item. In case a teamed item has got "wait -1" (no respawn), items of the team will stop spawing after that one has been picked up.
> 
> If "random" key is set, the respawn time can be anywhere between "wait - random" and "wait + random" seconds.
> 
> Unless you are planning a specific kind of gameplay, it's advisable to do not set "wait" or "count" keys, to do not mess with what players know about items timings and effects. If you want to limit an entity to make it viable on your map, you may rethink the layout of your map so the entity doesn't end overpowered.
> 
> Upon activation of the targets, all shaders/textures in the map with the shader/texture mentioned in targetShaderName will change to the shader/texture mentioned in targetShaderNewName. This is useful for on/off switches, for example.

(Merged the two descriptions, having care to reword those from older gamepack, which probably was not fully gpl - the main reason behind the whole gamepack rewrite)

Furthermore... is it just me, or do all the entities definitions lack the explanation of their SPAWNFLAGS?

**Comment by NeonKnightOA** [comment]
Can you create a pull request by modifying the respective fields in the .csv files?

**Comment by NeonKnightOA** [comment]
Item description tackled on NeonKnightOA/oagamepack@fd081c9d55408d36aadd925925dae1964b7f3b08.

As for spawnflags, I suppose you're talking about the .ent files. I still have no idea about how to tackle that one.

**Comment by The-Gig** [comment]
About the spawnflags:
I haven't checked this stuff in some time. My fault. At a certain point I thought that maybe the export script is faulty when exporting to one if the two formats, so a fix of the python/anaconda script would have been needed (nothing I may be capable of). But I'm not  sure about it, as I didn't complete the tests and some months passed since then...

**Comment by NeonKnightOA** [comment]
As far as I know, the problem was in the Python scripts. I guess @sago007  tried to incorporate them but haven't had the time or something like that. Can't remember now what he said.

**Comment by NeonKnightOA** [comment]
Since the note removal is already tackled, I've opened a new issue about spawnflags.
