### ISSUE TITLE
Missing item_botroam

### ISSUE THREAD

**Issue by The-Gig** [NeonKnightOA/oagamepack#6]
In current gamepack, item_botroam entity is absent from entities.ent and entities.def.
_Note for mappers reading this: I guess it can be still be used, by creating a different entity and then manually changing its "classname" key (and setting a "weight" of course)_.

This is its description in the old gamepack:

```
/*QUAKED item_botroam (1 0.5 0) (-8 -8 -8) (8 8 8) SUSPENDED
Game Function: An invisible entity which attracts a bot to it. Use to move bots to parts of a map that might otherwise not be used (NEW ENTITY).
-------- KEYS --------
weight: non-zero floating point value, most often in the range 0 to 400. (Higher values are allowed but keep in mind that the bot should also be attracted to normal items.  Don't make the weight value too high.
notfree : when set to 1, entity will not spawn in "Free for all" and "Tournament" modes.
notteam : when set to 1, entity will not spawn in "Teamplay" and "CTF" modes.
notsingle : when set to 1, entity will not spawn in Single Player mode (bot play mode).
-------- SPAWNFLAGS --------
SUSPENDED : item will spawn where it was placed in map and won't drop to the floor.
-------- NOTES --------
The item_botroam entity can be used when a bot does not roam the whole level or prefers to go to only specific areas. This (invisible) item can be placed in a map just like regular items. Nobody can actually pick up the item it's only used to attract bots to certain places of the map. The value is the weight of the roam_item is relative to the weight assigned other items in the map (each bot has its own weights). The bot character specific item weights are stored with the bot characters AI files ("botname"_i.c for items and "botname"_w.c for weapons) in the botfiles/bots/ sub-folder in the .pk3 file.*/
```

And this is how I think it may be re-added:

```
/*QUAKED item_botroam (1 0.5 0) (-8 -8 -8) (8 8 8) SUSPENDED
This is an invisible entity that can be used to invite bots to go to areas they are usually not interested into. They will try to touch it like it was an item to pick up, although there is nothing to actually pick up. It has got no effect on human players.
--------- KEYS --------
"weight" : floating point number used to set how much bots will be attracted by the entity. Usually between 1 and 400. Values higher than that are allowed, but usually not advisable.
"notfree" : If set to 1, this entity won't spawn in free-for-all gamemodes.
"notsingle" : If set to 1, this entity won't spawn in single-player mode.
"notteam" : If set to 1, this entity won't spawn in team-based gamemodes.
-------- SPAWNFLAGS --------
SUSPENDED : Instead of spawning on the floor as usual, the item spawns exactly where it is placed. Bots go for suspended items only if they can be reached with a jumppad or are in water.
-------- NOTES --------
Actual weight of the item is relative to those of the other items in the map, and depends from the weights of each bot, as specified in its "botname"_i.c (items) and "botname"_w.c (weapons) under botfiles/bots folder.*/
```

By the way, a thing I have never understood about item_botroam is if it has got a "default" weight or not...

Note: I tried to compare the entities list (right mouse button in 2d view) in a Radiant with current gamepack and in a Radiant with previous gamepack (probably this one <http://ingar.satgnu.net/gtkradiant/files/netradiant-20120705-win32.zip>) and _I haven't noticed_ other entities completely missing. There are however some entities which seem to lack some infos (examples: <https://github.com/NeonKnightOA/oagamepack/issues/4>, <https://github.com/NeonKnightOA/oagamepack/issues/5>).

**Comment by NeonKnightOA** [comment]
I thought we had this one. Unfortunately I'm unable to take a look by the moment. Can you create a pull request by modifying the .csv files?

**Comment by The-Gig** [comment]
I started to understand something about how this stuff works the last week. I more or less managed to fix the problems with target_speaker (https://github.com/NeonKnightOA/oagamepack/issues/4), but I haven't opened a pull request yet because there is still something I wish to check before that.

However I plan to try to see if I'm capable of adding and entry for item_botroam in the next days. But I need to find a "calm" day when I have some time to concentrate about it, as this thing of manually editing an 8-table database is something which isn't very easy for my brain!

**Comment by The-Gig** [comment]
I know I am months late with these fixes. Sorry. I'm busy with mapping at the moment.
However, I'm writing down as a reminder another issue with the gamepack I'm planning to fix when I find time and will: _trigger_hurt spawnfags_: "silent" is 4 (not 2); "no_protection" is 8 (not 4); slow is 16 (not 8).

**Comment by NeonKnightOA** [comment]
Problem confirmed. There was a missing line in one of the CSV files.

Fixed in NeonKnightOA/oagamepack@395377d2686a9a7b7cbfb959da9f2b6b6a1853cc.

**Comment by The-Gig** [comment]
Thanks. But it looks like trigger_hurt spawnflags have not been fixed, so they are still messed up.
I know trigger_hurt was not the initial "issue" and I mentioned it later... however please forgive me if I reopen this issue instead of creating a new one...

**Comment by The-Gig** [comment]
I was from mobile yesterday. I'm from PC now, so I created a proper "issue" about trigger_hurt problem: https://github.com/NeonKnightOA/oagamepack/issues/7
Maybe it may be caused by some error in the python scripts and @sago007 may help us?

(Closing this issue, we can continue in the new one).
